library(tibble)
library(dplyr)

df <- readRDS("../outputs/ukb_collapsed4.rds")

df <- df %>%
  rename_with(
    ~ gsub("\\.", "_", .x),
    starts_with("med_")
  )

colnames(df) <- gsub("\\.0\\.0$", "", colnames(df))
names(df) <- gsub("\\.", "_", names(df))

colnames_table <- tibble(
  original_name = names(df),
  plot_label = NA_character_
)

print(colnames_table)

plot_labels <- c(
  "sex" = "Sex*",
  "dob" = "Date of birth",
  "waist_circumference_cm" = "Waist circumference",
  "hip_circumference_cm" = "Hip circumference",
  "attending_assessment_date" = "Assessment date",
  "n_treatments" = "No. of treatments",
  "hh_income_pre_tax" = "Income",
  "job_walk_stand_yn" = "Walking/standing at work",
  "age_full_edu" = "Age finished education",
  "risky_driving_speeding" = "Risky driving",
  "sleep_duration" = "Sleep duration",
  "sleep_insomnia" = "Insomnia",
  "diet_tea" = "Tea intake",
  "diet_coffee" = "Coffee intake",
  "diet_water" = "Water intake",
  "mh_loneliness" = "Loneliness",
  "mh_social_support_confide" = "Confide in others",
  "sur_major_surgery" = "Major surgery",
  "dis_diabetes_doc_yn" = "Diagnosed diabetes",
  "dis_cancer_doc_yn" = "Diagnosed cancer",
  "dis_age_highbp" = "Age at hypertension diagnosis",
  "dis_age_diabetes" = "Age at diabetes diagnosis",
  "pregnant_yn" = "Pregnancy status",
  "yr_imm_uk" = "Year of UK immigration",
  "dis_age_mi" = "Age at MI diagnosis",
  
  "med_chol_bp_dm_or_horm_yn_0_0" = "Chol/BP/DM/hormone med (1)",
  "med_chol_bp_dm_or_horm_yn_0_1" = "Chol/BP/DM/hormone med (2)",
  "med_chol_bp_dm_or_horm_yn_0_2" = "Chol/BP/DM/hormone med (3)",
  "med_chol_bp_dm_or_horm_yn_0_3" = "Chol/BP/DM/hormone med (4)",
  
  "med_symptom_relief_yn_0_0" = "Symptom relief med (1)",
  "med_symptom_relief_yn_0_1" = "Symptom relief med (2)",
  "med_symptom_relief_yn_0_2" = "Symptom relief med (3)",
  "med_symptom_relief_yn_0_3" = "Symptom relief med (4)",
  "med_symptom_relief_yn_0_4" = "Symptom relief med (5)",
  "med_symptom_relief_yn_0_5" = "Symptom relief med (6)",
  
  "med_chol_bp_dm_yn_0_0" = "Chol/BP/DM med (1)",
  "med_chol_bp_dm_yn_0_1" = "Chol/BP/DM med (2)",
  "med_chol_bp_dm_yn_0_2" = "Chol/BP/DM med (3)",
  
  "med_pain_cons_hrt__0_0" = "Pain/const./HRT med (1)",
  "med_pain_cons_hrt__0_1" = "Pain/const./HRT med (2)",
  "med_pain_cons_hrt__0_2" = "Pain/const./HRT med (3)",
  "med_pain_cons_hrt__0_3" = "Pain/const./HRT med (4)",
  "med_pain_cons_hrt__0_4" = "Pain/const./HRT med (5)",
  
  "smoking_status" = "Smoking status",
  "mh_BPD_MD" = "BPD / major depression",
  "mh_neuroticism" = "Neuroticism",
  "smoking_pack_years" = "Smoking pack-years",
  "eth_bg" = "Ethnic background*",
  "bmi" = "BMI",
  "arterial_stiffness_index" = "Arterial stiffness index",
  "age_at_recruitment" = "Age at recruitment*",
  "MET_summed" = "MET-min/week",
  "dis_age_copd" = "Age at COPD diagnosis",
  "dis_age_pulmonary_fibrosis" = "Age at pulmonary fibrosis diagnosis",
  "body_fat_pct" = "Body fat (%)",
  
  "air_no2_2010" = "NO2 air pollution",
  "air_pm10_2010" = "PM10 air pollution",
  "air_pm2_5_2010" = "PM2.5 air pollution",
  "noise24h" = "24-hour noise level",
  "green_greenspace_300m" = "Greenspace (%) (300 m)",
  "green_garden_300m" = "Domestic garden (%) (300 m)",
  "blue_water_300m" = "Water (%) (300 m)",
  "green_natural_300m" = "Natural environment (%) (300 m)",
  "blue_distance_coast" = "Distance to coast",
  
  "rbc_count" = "RBC count",
  "haemoglobin_concent" = "Haemoglobin concentration",
  "haematocrit_percent" = "Haematocrit (%)",
  "mean_corp_vol" = "Mean corpuscular volume",
  "mean_corp_haem" = "Mean corpuscular haemoglobin",
  "mean_corp_haem_con" = "Mean corpuscular haemoglobin conc.",
  "rdw" = "RBC distribution width",
  "platelet_count" = "Platelet count",
  "platelet_crit" = "Platelet crit",
  "mean_platelet_volume" = "Mean platelet volume",
  "platelet_distribution_width" = "Platelet distribution width",
  "lymphocyte_count" = "Lymphocyte count",
  "monocyte_count" = "Monocyte count",
  "neutrophil_count" = "Neutrophil count",
  "eosinophil_count" = "Eosinophil count",
  "basophil_count" = "Basophil count",
  "nucleated_rbc_count" = "Nucleated RBC count",
  "lymphocyte_percentage" = "Lymphocyte (%)",
  "monocyte_percentage" = "Monocyte (%)",
  "neutrophil_percentage" = "Neutrophil (%)",
  "eosinophil_percentage" = "Eosinophil (%)",
  "basophil_percentage" = "Basophil (%)",
  "nucleated_rbc_percentage" = "Nucleated RBC (%)",
  "reticulocyte_percentage" = "Reticulocyte (%)",
  "reticulocyte_count" = "Reticulocyte count",
  "mean_reticulocyte_volume" = "Mean reticulocyte volume",
  "mean_sphered_cell_volume" = "Mean sphered cell volume",
  "immature_reticulocyte_frac" = "Immature reticulocyte fraction",
  "hlr_reticulocyte_percentage" = "HLR reticulocyte (%)",
  "hlr_reticulocyte_count" = "HLR reticulocyte count",
  
  "microalbuminuria_urine" = "Microalbumin in urine",
  "albumin" = "Albumin",
  "alkaline_phos" = "Alkaline phosphatase",
  "alanine_amino" = "Alanine aminotransferase",
  "apolipoprotein_a" = "Apolipoprotein A",
  "apolipoprotein_b" = "Apolipoprotein B",
  "aspartate_amino" = "Aspartate aminotransferase",
  "bilirubin_direct" = "Direct bilirubin",
  "urea" = "Urea",
  "calcium" = "Calcium",
  "cholesterol" = "Cholesterol",
  "creatinine" = "Creatinine",
  "crp" = "CRP",
  "cystatin_c" = "Cystatin C",
  "gamma_glumy_tran" = "Gamma-GT",
  "glucose" = "Glucose",
  "hba1c" = "HbA1c",
  "hdl" = "HDL",
  "igf1" = "IGF-1",
  "ldl" = "LDL",
  "lipoprotein_a" = "Lipoprotein(a)",
  "oestradiol" = "Oestradiol",
  "phosphate" = "Phosphate",
  "rheumatoid_factor" = "Rheumatoid factor",
  "shbg" = "SHBG",
  "bilirubin_total" = "Total bilirubin",
  "testosterone" = "Testosterone",
  "triglycerides" = "Triglycerides",
  "urate" = "Urate",
  "vitamin_d" = "Serum Vitamin D",
  
  "date_of_death" = "Date of death",
  "dis_date_of_cancer" = "Date of cancer diagnosis",
  "dis_history_cancer_tumour" = "Cancer/tumour history",
  "saturated_fat" = "Saturated fat",
  "polyunsat_fat" = "Polyunsaturated fat",
  "vitamin_b6" = "Food/Supp. Vitamin B6",
  "vitamin_b12" = "Food/Supp. Vitamin B12",
  "dis_chronic_hepatitis" = "Chronic hepatitis",
  "dis_insulin_dep_diabetes" = "Insulin-dependent diabetes",
  "dis_non_insulin_dep_diabetes" = "Non-insulin-dependent diabetes",
  "dis_schizophrenia" = "Schizophrenia",
  "mh_depr_single_icd" = "Single-episode depression",
  "mh_depr_recurrent_icd" = "Recurrent depression",
  "mh_anxiety_phobic_icd" = "Phobic anxiety",
  "mh_anxiety_general_icd" = "Generalised anxiety",
  "dis_parkinsons_disease" = "Parkinson's disease",
  "dis_alzheimers_disease" = "Alzheimer's disease",
  "dis_multiple_sclerosis" = "Multiple sclerosis",
  "dis_migraine" = "Migraine",
  "dis_other_headaches" = "Other headaches",
  "dis_sleep_disorders" = "Sleep disorders",
  "dis_dt_l10_first" = "High PB (Primary)",
  "dis_hypertensive_renal_disease" = "Hypertensive renal disease",
  "dis_hypertensive_heart_renal_disease" = "Hypertensive heart/renal disease",
  "dis_asthma" = "Asthma",
  "dis_crohns_disease" = "Crohn's disease",
  "dis_ulcerative_colitis" = "Ulcerative colitis",
  "dis_alcoholic_liver_disease" = "Alcoholic liver disease",
  "dis_liver_fibrosis_and_cirrhosis" = "Liver fibrosis/cirrhosis",
  "dis_psoriasis" = "Psoriasis",
  "dis_lupus" = "Lupus",
  "dis_rheumatoid_arthritis" = "Rheumatoid arthritis",
  "dis_chronic_renal_failure" = "Chronic renal failure",
  
  "sys_bp" = "Systolic BP",
  "dia_bp" = "Diastolic BP",
  "fvc" = "FVC",
  "fev1" = "FEV1",
  "qualifications" = "Qualifications",
  "current_employ_status" = "Employment Status",
  "dis_cvd_doc_yn" = "Diagnosed CVD",
  "outcome" = "Outcome",
  "sedentary_total_hours" = "Sedentary time (h)",
  "diet_score" = "Diet score",
  "alcohol_status_with_freq" = "Alcohol consumption"
)

domain_map <- c(
  # Demographics & Socioeconomic
  "sex" = "Demographics & Socioeconomic",
  "dob" = "Demographics & Socioeconomic",
  "eth_bg" = "Demographics & Socioeconomic",
  "hh_income_pre_tax" = "Demographics & Socioeconomic",
  "qualifications" = "Demographics & Socioeconomic",
  "current_employ_status" = "Demographics & Socioeconomic",
  "age_full_edu" = "Demographics & Socioeconomic",
  "age_at_recruitment" = "Demographics & Socioeconomic",
  "yr_imm_uk" = "Demographics & Socioeconomic",
  
  # Lifestyle
  "smoking_status" = "Lifestyle",
  "smoking_pack_years" = "Lifestyle",
  "alcohol_status_with_freq" = "Lifestyle",
  "diet_tea" = "Lifestyle",
  "diet_coffee" = "Lifestyle",
  "diet_water" = "Lifestyle",
  "diet_score" = "Lifestyle",
  "saturated_fat" = "Lifestyle",
  "polyunsat_fat" = "Lifestyle",
  "vitamin_b6" = "Lifestyle",
  "vitamin_b12" = "Lifestyle",
  "sleep_duration" = "Lifestyle",
  "sleep_insomnia" = "Lifestyle",
  "MET_summed" = "Lifestyle",
  "sedentary_total_hours" = "Lifestyle",
  "risky_driving_speeding" = "Lifestyle",
  "job_walk_stand_yn" = "Lifestyle",
  "mh_neuroticism" = "Lifestyle",
  "mh_loneliness" = "Lifestyle",
  "mh_social_support_confide" = "Lifestyle",
  
  # Clinical
  "bmi" = "Clinical",
  "body_fat_pct" = "Clinical",
  "waist_circumference_cm" = "Clinical",
  "hip_circumference_cm" = "Clinical",
  "sys_bp" = "Clinical",
  "dia_bp" = "Clinical",
  "arterial_stiffness_index" = "Clinical",
  "fvc" = "Clinical",
  "fev1" = "Clinical",
  "n_treatments" = "Clinical",
  "pregnant_yn" = "Clinical",
  
  # Biomarkers
  "rbc_count" = "Biomarkers",
  "haemoglobin_concent" = "Biomarkers",
  "haematocrit_percent" = "Biomarkers",
  "mean_corp_vol" = "Biomarkers",
  "mean_corp_haem" = "Biomarkers",
  "mean_corp_haem_con" = "Biomarkers",
  "rdw" = "Biomarkers",
  "platelet_count" = "Biomarkers",
  "platelet_crit" = "Biomarkers",
  "mean_platelet_volume" = "Biomarkers",
  "platelet_distribution_width" = "Biomarkers",
  "lymphocyte_count" = "Biomarkers",
  "monocyte_count" = "Biomarkers",
  "neutrophil_count" = "Biomarkers",
  "eosinophil_count" = "Biomarkers",
  "basophil_count" = "Biomarkers",
  "nucleated_rbc_count" = "Biomarkers",
  "lymphocyte_percentage" = "Biomarkers",
  "monocyte_percentage" = "Biomarkers",
  "neutrophil_percentage" = "Biomarkers",
  "eosinophil_percentage" = "Biomarkers",
  "basophil_percentage" = "Biomarkers",
  "nucleated_rbc_percentage" = "Biomarkers",
  "reticulocyte_percentage" = "Biomarkers",
  "reticulocyte_count" = "Biomarkers",
  "mean_reticulocyte_volume" = "Biomarkers",
  "mean_sphered_cell_volume" = "Biomarkers",
  "immature_reticulocyte_frac" = "Biomarkers",
  "hlr_reticulocyte_percentage" = "Biomarkers",
  "hlr_reticulocyte_count" = "Biomarkers",
  "microalbuminuria_urine" = "Biomarkers",
  "albumin" = "Biomarkers",
  "alkaline_phos" = "Biomarkers",
  "alanine_amino" = "Biomarkers",
  "apolipoprotein_a" = "Biomarkers",
  "apolipoprotein_b" = "Biomarkers",
  "aspartate_amino" = "Biomarkers",
  "bilirubin_direct" = "Biomarkers",
  "bilirubin_total" = "Biomarkers",
  "urea" = "Biomarkers",
  "calcium" = "Biomarkers",
  "cholesterol" = "Biomarkers",
  "creatinine" = "Biomarkers",
  "crp" = "Biomarkers",
  "cystatin_c" = "Biomarkers",
  "gamma_glumy_tran" = "Biomarkers",
  "glucose" = "Biomarkers",
  "hba1c" = "Biomarkers",
  "hdl" = "Biomarkers",
  "igf1" = "Biomarkers",
  "ldl" = "Biomarkers",
  "lipoprotein_a" = "Biomarkers",
  "oestradiol" = "Biomarkers",
  "phosphate" = "Biomarkers",
  "rheumatoid_factor" = "Biomarkers",
  "shbg" = "Biomarkers",
  "testosterone" = "Biomarkers",
  "triglycerides" = "Biomarkers",
  "urate" = "Biomarkers",
  "vitamin_d" = "Biomarkers",
  
  # Environment
  "air_no2_2010" = "Environment",
  "air_pm10_2010" = "Environment",
  "air_pm2_5_2010" = "Environment",
  "noise24h" = "Environment",
  "green_greenspace_300m" = "Environment",
  "green_garden_300m" = "Environment",
  "green_natural_300m" = "Environment",
  "blue_water_300m" = "Environment",
  "blue_distance_coast" = "Environment",
  
  # Disease
  "sur_major_surgery" = "Disease", 
  "mh_BPD_MD" = "Disease",
  "mh_depr_single_icd" = "Disease",
  "mh_depr_recurrent_icd" = "Disease",
  "mh_anxiety_phobic_icd" = "Disease",
  "mh_anxiety_general_icd" = "Disease",
  "dis_cvd_doc_yn" = "Disease",
  "dis_dt_l10_first" = "Disease",
  "dis_diabetes_doc_yn" = "Disease",
  "dis_insulin_dep_diabetes" = "Disease",
  "dis_non_insulin_dep_diabetes" = "Disease",
  "dis_age_highbp" = "Disease",
  "dis_age_diabetes" = "Disease",
  "dis_age_mi" = "Disease",
  "dis_cancer_doc_yn" = "Disease",
  "dis_history_cancer_tumour" = "Disease",
  "dis_date_of_cancer" = "Disease",
  "dis_asthma" = "Disease",
  "dis_age_copd" = "Disease",
  "dis_age_pulmonary_fibrosis" = "Disease",
  "dis_parkinsons_disease" = "Disease",
  "dis_alzheimers_disease" = "Disease",
  "dis_multiple_sclerosis" = "Disease",
  "dis_crohns_disease" = "Disease",
  "dis_ulcerative_colitis" = "Disease",
  "dis_alcoholic_liver_disease" = "Disease",
  "dis_liver_fibrosis_and_cirrhosis" = "Disease",
  "dis_chronic_hepatitis" = "Disease",
  "dis_chronic_renal_failure" = "Disease",
  "dis_hypertensive_renal_disease" = "Disease",
  "dis_hypertensive_heart_renal_disease" = "Disease",
  "dis_psoriasis" = "Disease",
  "dis_lupus" = "Disease",
  "dis_rheumatoid_arthritis" = "Disease",
  "dis_migraine" = "Disease",
  "dis_other_headaches" = "Disease",
  "dis_sleep_disorders" = "Disease",
  "dis_schizophrenia" = "Disease",
  
  # Medications
  "med_chol_bp_dm_or_horm_yn_0_0" = "Medications",
  "med_chol_bp_dm_or_horm_yn_0_1" = "Medications",
  "med_chol_bp_dm_or_horm_yn_0_2" = "Medications",
  "med_chol_bp_dm_or_horm_yn_0_3" = "Medications",
  "med_symptom_relief_yn_0_0" = "Medications",
  "med_symptom_relief_yn_0_1" = "Medications",
  "med_symptom_relief_yn_0_2" = "Medications",
  "med_symptom_relief_yn_0_3" = "Medications",
  "med_symptom_relief_yn_0_4" = "Medications",
  "med_symptom_relief_yn_0_5" = "Medications",
  "med_chol_bp_dm_yn_0_0" = "Medications",
  "med_chol_bp_dm_yn_0_1" = "Medications",
  "med_chol_bp_dm_yn_0_2" = "Medications",
  "med_pain_cons_hrt__0_0" = "Medications",
  "med_pain_cons_hrt__0_1" = "Medications",
  "med_pain_cons_hrt__0_2" = "Medications",
  "med_pain_cons_hrt__0_3" = "Medications",
  "med_pain_cons_hrt__0_4" = "Medications",
  
  # Study Timing
  "attending_assessment_date" = "Study Timing",
  "date_of_death" = "Study Timing",
  "outcome" = "Study Timing"
)

label_table <- data.frame(
  variable = names(plot_labels),
  plot_label = unname(plot_labels),
  domain = unname(domain_map[names(plot_labels)]),
  stringsAsFactors = FALSE
)

# optional check for any variables missing a domain assignment
missing_domain <- label_table %>%
  filter(is.na(domain))

print(missing_domain)

length(plot_labels)
nrow(label_table)


domain_colors <- c(
  "Demographics & Socioeconomic" = "#A6CEE3",
  "Lifestyle"                    = "#B2DF8A",
  "Clinical"                     = "#CAB2D6",
  "Biomarkers"                   = "#FDBF6F",
  "Environment"                  = "#8DD3C7",
  "Disease"                      = "#FB9A99", #mental health removed
  "Medications"                  = "#FFFFB3",
  "Study Timing"                 = "#D9D9D9"
)

label_table <- label_table %>%
  mutate(domain_color = domain_colors[domain])


write.csv(label_table, "../outputs/plot_labels_domain.csv", row.names = FALSE)


